apiVersion: v1
kind: Namespace
metadata:
  name: theia-ide
  labels:
    app: theia-ide

#---
#apiVersion: networking.k8s.io/v1beta1
#kind: Ingress
#metadata:
#  name: theia-next
#  namespace: theia-ide
#  annotations:
#    kubernetes.io/ingress.class: nginx
#spec:
#  rules:
#    - host: theia.your_domain
#      http:
#        paths:
#          - backend:
#              serviceName: theia-next
#              servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: theia-ide
  namespace: theia-ide
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: theia-ide
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: theia-ide
  name: theia-ide
  namespace: theia-ide
spec:
  selector:
    matchLabels:
      app: theia-ide
  replicas: 1
  template:
    metadata:
      labels:
        app: theia-ide
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - image: quay.io/kubermatic-labs/theia-ide:2020-12-07
          #image: theiaide/theia-go:next
          imagePullPolicy: Always
          name: theia-next
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: '/home/project'
              name: theia-home
      volumes:
        - name: theia-home
          persistentVolumeClaim:
            claimName: theia-home
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: theia-home
  namespace: theia-ide
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi