apiVersion: kubermatic.k8c.io/v1
kind: Seed
metadata:
  name: kubermatic
  namespace: kubermatic
spec:
  # these two fields are only informational
  country: DE
  location: Frankfurt

  # List of datacenters where this seed cluster is allowed to create clusters in
  # In this example, user cluster will be deployed in eu-central-1 on AWS.
  datacenters:
    aws-eu-central-1a:
      country: DE
      location: EU (Frankfurt)
      spec:
        aws:
          images: null
          region: eu-central-1
        enforceAuditLogging: false
        enforcePodSecurityPolicy: false

  etcdBackupRestore:
    defaultDestination: minio
    destinations:
      minio:
        # use the bucket name chosen for the create-minio-backup-bucket Job from above.
        bucketName: kkpbackup
        credentials:
          name: kubermatic-s3-credentials
          namespace: kube-system
        endpoint: http://minio.minio.svc.cluster.local:9000

  # reference to the kubeconfig to use when connecting to this seed cluster
  kubeconfig:
    name: kubeconfig-cluster
    namespace: kubermatic

  mla:
    userClusterMLAEnabled: true
