##### kubeadm installation
FROM amd64/rockylinux:8

### for dind kubeadm
### docker run -it --privileged cruizba/ubuntu-dind
### kubeadm join xxxx --token xxxx --ignore-preflight-errors=Swap,SystemVerification
# TODO fix systemd startup
#FROM cruizba/ubuntu-dind

ARG K8S_VERSION

COPY kubeadm-generator-install.sh /kubeadm-install.sh

RUN chmod +x /kubeadm-install.sh && /kubeadm-install.sh ${K8S_VERSION}
