{{- range $job := $.Values.rcloneS3Syncer.job }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $job.name }}-source-config
type: Opaque
data:
  RCLONE_CONFIG_SOURCE_TYPE: {{ default "s3" $job.source.type | b64enc | quote }}
  RCLONE_CONFIG_SOURCE_PROVIDER: {{ default "minio" $job.source.provider | b64enc | quote }}
  RCLONE_CONFIG_SOURCE_ENDPOINT: {{ default "https://s3.amazonaws.com" $job.source.endpoint | b64enc | quote }}
  RCLONE_CONFIG_SOURCE_ACCESS_KEY_ID: {{ default "AKIAIOSFODNN7EXAMPLE" $job.source.accessKeyID | b64enc | quote }}
  RCLONE_CONFIG_SOURCE_SECRET_ACCESS_KEY: {{ default "wJalrXUtneFEMIK7MDENGbPxRfiyCYEXAMPLEKEY" $job.source.secretAccessKey | b64enc | quote }}
  SOURCE_BUCKET: {{ default "source-bucket" $job.source.bucket | b64enc | quote }}
  RCLONE_CONFIG_SOURCE_ACL: {{ default "private" $job.source.acl | b64enc | quote }}
---
{{- end }}
