{{- range $job := $.Values.rcloneS3Syncer.job }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $job.name }}-target-config
type: Opaque
data:
  RCLONE_CONFIG_TARGET_TYPE: {{ default "s3" $job.target.type | b64enc | quote }}
  RCLONE_CONFIG_TARGET_ACCOUNT: {{ default "minio" $job.target.account | b64enc | quote }}
  RCLONE_CONFIG_TARGET_KEY: {{ default "https://s3.amazonaws.com" $job.target.key | b64enc | quote }}
  TARGET_BUCKET: {{ default "minio" $job.target.bucket | b64enc | quote }}
---
{{- end }}
