vcenter_datacenter = "dc-1"
vcenter_cluster = "cl-1"
vcenter_datastore = "dsc-1/exsi-nas"
vcenter_network = "Loodse Default"
vcenter_template = "my-vm-templates/ubuntu-bionic-18.04-cloudimg"
output_vm_folder = "my-vm-templates"
output_vm_name = "packer-ubuntu-18.04"
