apiVersion: v1
kind: ConfigMap
metadata:
  name: flatcar-linux-resolved-overwrite-conf
  namespace: kube-system
data:
  resolv.conf: |
    nameserver 1.1.1.1
    nameserver 8.8.8.8
    search .
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: flatcar-linux-resolved-overwrite
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: flatcar-linux-resolved-overwrite
  template:
    metadata:
      labels:
        name: flatcar-linux-resolved-overwrite
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: v1.machine-controller.kubermatic.io/operating-system
                operator: In
                values:
                - flatcar
            - matchExpressions:
              - key: v1.kubeone.io/operating-system
                operator: In
                values:
                - flatcar
      containers:
      - name: flatcar-linux-resolved-overwrite
        image: alpine:3.20.3
        command:
        - /bin/sh
        - -c
        - |
          apk add --no-cache bash util-linux
          while true; do
            diff /tmp/conf/resolv.conf /tmp/resolv.conf.bak >/dev/null 2>&1
            if [ $? != 0 ]; then
              cp /tmp/conf/resolv.conf /tmp/resolv.conf.bak
              export resolv=$(cat /tmp/conf/resolv.conf)
              nsenter -t 1 -m -u -i -n -p -- bash -c "${STARTUP_SCRIPT}"
              echo "DNS config was updated"
            else
              echo "DNS config is up to date"
            fi
            sleep 10
          done
        env:
        - name: STARTUP_SCRIPT
          value: |
            set -xeuo pipefail
            echo "$resolv" > /etc/resolv.conf
            systemctl restart systemd-resolved
        volumeMounts:
        - name: flatcar-linux-resolved-overwrite-conf-volume
          mountPath: /tmp/conf
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 16Mi
        securityContext:
          privileged: true
      volumes:
      - name: flatcar-linux-resolved-overwrite-conf-volume
        configMap:
          name: flatcar-linux-resolved-overwrite-conf
      hostPID: true
      terminationGracePeriodSeconds: 30
