apiVersion: v1
kind: Namespace
metadata:
  name: loki-stack
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: loki-stack
spec:
  releaseName: loki-stack
  chart:
    repository: https://grafana.github.io/loki/charts
    name: loki-stack
    version: v0.40.0
  values:
    grafana:
      enabled: true
      adminPassword: {{ .Variables.adminPassword }}
    prometheus:
      enabled: true
      alertmanager:
        persistentVolume:
          enabled: false
      server:
        persistentVolume:
          storageClassName: {{ .Variables.storageClassName }}
          enabled: true
    loki:
      persistence:
        enabled: true
        storageClassName: {{ .Variables.storageClassName }}
        size: 10Gi