kind: PodPreset
apiVersion: settings.k8s.io/v1alpha1
metadata:
  name: replace-root-cas
spec:
  selector:
    matchLabels: {}
  volumeMounts:
    - mountPath: /etc/ssl/certs
      name: root-cas
      readOnly: true
  volumes:
    - name: root-cas
      hostPath:
        path: /etc/ssl/certs
        type: Directory
