---
# Source: velero/templates/deployment.yaml
# Copyright 2020 The Kubermatic Kubernetes Platform contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero
  namespace: velero
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/version: 'v1.8.1'
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: velero
  template:
    metadata:
      labels:
        app.kubernetes.io/name: velero
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8085"
        kubermatic.io/chart: velero
    spec:
      restartPolicy: Always
      containers:
      - name: velero
        image: 'docker.io/velero/velero:v1.8.1'
        imagePullPolicy: IfNotPresent
        command:
        - /velero
        args:
        - server
        - '--default-backup-storage-location=aws'
        env:
        - name: VELERO_SCRATCH_DIR
          value: /scratch
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /credentials/aws/creds
        volumeMounts:
        - name: plugins
          mountPath: /plugins
        - name: scratch
          mountPath: /scratch
        - name: aws-credentials
          mountPath: /credentials/aws
        ports:
        - name: metrics
          containerPort: 8085
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 50Mi
      initContainers:
      - image: docker.io/velero/velero-plugin-for-aws:v1.1.0
        imagePullPolicy: IfNotPresent
        name: velero-plugin-for-aws
        volumeMounts:
        - mountPath: /target
          name: plugins
      volumes:
      - name: plugins
        emptyDir: {}
      - name: scratch
        emptyDir: {}
      - name: aws-credentials
        secret:
          secretName: aws-credentials
      serviceAccountName: velero
      nodeSelector:
        {}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kubermatic.io/type
                operator: In
                values:
                - stable
            weight: 100
      tolerations:
        []
