---
# Source: velero/templates/secrets.yaml
# This secret contains the password with which restic is encrypting all
# the backups. It must be called "velero-restic-credentials" and contain
# the key "repository-password".
{{ if .Variables.deployRestic }}

apiVersion: v1
kind: Secret
metadata:
  name: velero-restic-credentials
  namespace: velero
type: Opaque
data:
  repository-password: {{ .Variables.resticPassword | b64enc | quote }}

{{ end }}

---
# Source: velero/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: velero
type: Opaque
data:
  creds: {{ (printf "[default]\naws_access_key_id=%s\naws_secret_access_key=%s\n" .Variables.awsAccessKey .Variables.awsSecretAccessKey) | b64enc | quote }}
---
# Source: velero/templates/secrets.yaml
# Copyright 2020 The Kubermatic Kubernetes Platform contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
