apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "vmware-exporter.fullname" . }}
  labels:
    app: {{ template "vmware-exporter.name" . }}
    chart: {{ template "vmware-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "vmware-exporter.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "vmware-exporter.name" . }}
        release: {{ .Release.Name }}
      annotations:
{{- with .Values.podAnnotations }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9272
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ template "vmware-exporter.fullname" . }}-config
            - secretRef:
                name: {{ if not .Values.vsphere.existingSecret }}{{ template "vmware-exporter.fullname" . }}-secret{{ else }}{{ .Values.vsphere.existingSecret }}{{ end }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
        {{- with .Values.securityContext }}
          securityContext:
        {{- toYaml . | nindent 12 }}
        {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.podSecurityContext }}
      securityContext:
    {{- toYaml . | nindent 8 }}
    {{- end }}
