apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationDefinition
metadata:
  name: aquasec-airgapped-cybercenter
spec:
  description: Component Cyber Center - Aqua Security provides security for the cloud-native world inside any CNCF-Kubernetes. This application installs a copy of the Threat intelligence Database (Aqua CyberCenter) inside a cluster. The only purpose of this is to be in accordance to air-gapped environments, which shall not have any internet connection / upstream communication. The CyberCenter needs to be connected with your local Aqua Server installation.
  method: helm
  defaultDeployOptions:
    helm:
      atomic: true
      wait: true
      timeout: "5m"
  versions:
  - template:
      source:
        git:
          path: cyber-center
          ref:
            branch: 2022.4
          remote: https://github.com/aquasecurity/aqua-helm