apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationDefinition
metadata:
  name: aquasec-server
spec:
  description: Aqua Security provides security for the cloud-native world inside any CNCF-Kubernetes. This application will install an Aqua Server instance in the cluster to provide visibility and runtime security for it.
  method: helm
  defaultDeployOptions:
    helm:
      atomic: true
      wait: true
      timeout: "5m"
  versions:
  - template:
      source:
        git:
          path: server
          ref:
            branch: 2022.04
          remote: https://github.com/aquasecurity/aqua-helm.git