apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationDefinition
metadata:
  name: aquasec-supplychain
spec:
  description: Aqua Security provides security for the cloud-native world inside any CNCF-Kubernetes. This application installs additional local scanner and routing pods inside a cluster from which a local / self-hosted SCM shall be scanned. The components require and will establish a connection to your SaaS based Aqua Security installation.
  method: helm
  defaultDeployOptions:
    helm:
      atomic: true
      wait: true
      timeout: "5m"
  versions:
  - template:
      source:
        git:
          path: codesec-agent
          ref:
            branch: 2022.04
          remote: https://github.com/aquasecurity/aqua-helm.git