apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationDefinition
metadata:
  name: argocd
spec:
  description: Argo CD - Declarative Continuous Delivery for Kubernetes.
  method: helm
  versions:
  - template:
      source:
        helm:
          chartName: argo-cd
          chartVersion: 5.4.3
          url: https://argoproj.github.io/argo-helm
    version: 2.4.11
  # Update this to feed the default values.yaml to the application. Else set it empty {}
  defaultValues:
    server:
      certificate:
        enabled: true
        domain: argocd.xxxx.lab.kubermatic.io
        issuer:
          group: cert-manager.io
          kind: ClusterIssuer
          name: letsencrypt-prod
        secretName: argocd-tls
      ingress:
        enabled: true
        https: true
        hosts:
        - argocd.xxxx.lab.kubermatic.io
        ingressClassName: 'nginx'
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          kubernetes.io/tls-acme: 'true'
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        tls: 
        - secretName: argocd-tls
          hosts:
            - argocd.xxxx.lab.kubermatic.io
