apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationDefinition
metadata:
  name: echoserver
spec:
  description: An echo server is a server that replicates the request sent by the client and sends it back.
  method: helm
  versions:
  - template:
      source:
        helm:
          chartName: echo-server
          chartVersion: 0.5.0
          url: https://ealenn.github.io/charts
    version: 0.7.0
  # During the applicationdefinition creation time if the defaultValues is updated, then it is render for override during the application creation process from UI.
  # By default, it is set empty.
  defaultValues:
    ingress:
      enabled: true
      hosts:
      - host: echo.xxxx.lab.kubermatic.io
        paths:
        - /
      ingressClassName: 'nginx'
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/tls-acme: 'true'
      tls: 
        - secretName: echoserver-tls
          hosts:
          - echo.xxxx.lab.kubermatic.io
