# Example of an ApplicationDefinition
apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationDefinition
metadata:
  name: eclipse-che
spec:
  description: A Helm chart for deploying Eclipse Che on a Kubernetes or Openshift cluster.
  method: helm
  versions:
  - template:
      source:
        git:
          path: components/eclipse-che
          ref:
            branch: master
          remote: https://github.com/kubermatic/community-components
    version: 7.55.0
  # During the applicationdefinition creation time if the defaultValues is updated, then it is render for override during the application creation process from UI.
  # By default, it is set empty.
  defaultValues:
    networking:
      auth:
        identityProviderURL: "https://xxxxx.lab.kubermatic.io/dex"
        oAuthClientName: "kubermaticIssuer"
        oAuthSecret: "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
      domain: eclipse-che.xxxxx.lab.kubermatic.io
