# Example of an ApplicationDefinition
apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationDefinition
metadata:
  name: eclipse-che
spec:
  description: A Helm chart for deploying Eclipse Che on a Kubernetes or Openshift cluster.
  method: helm
  versions:
  - template:
      source:
        git:
          path: components/eclipse-che
          ref:
            branch: master
          remote: https://github.com/kubermatic/community-components
    version: 7.53.0
  # Update this to feed the default values.yaml to the application. Else set it empty {}
  defaultValues:
    networking:
      auth:
        identityProviderURL: "https://xxxxx.lab.kubermatic.io/dex"
        oAuthClientName: "kubermaticIssuer"
        oAuthSecret: "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
      domain: eclipse-che.xxxxx.lab.kubermatic.io
