apiVersion: kubermatic.k8c.io/v1
clusterLabels:
  is-credential-preset: "true"
  project-id: dl6kxzf8br
  type: demo
credential: credentials-xxx-crd-cluster-id
kind: ClusterTemplate
metadata:
  annotations:
    kubermatic.io/initial-machinedeployment-request: |
      {
        "metadata": {
          "name": "cluster-template-crd-example-vsphere-node",
          "namespace": "kube-system",
          "creationTimestamp": null,
          "annotations": {
            "k8c.io/operating-system-profile": "osp-ubuntu"
          },
          "finalizers": [
            "foregroundDeletion"
          ]
        },
        "spec": {
          "replicas": 2,
          "selector": {
            "matchLabels": {
              "machine": "cluster-template-crd-example-vsphere-node"
            }
          },
          "template": {
            "metadata": {
              "creationTimestamp": null,
              "labels": {
                "machine": "cluster-template-crd-example-vsphere-node"
              }
            },
            "spec": {
              "metadata": {
                "creationTimestamp": null,
                "labels": {}
              },
              "providerSpec": {
                "value": {
                  "sshPublicKeys": [],
                  "caPublicKey": "",
                  "cloudProvider": "vsphere",
                  "cloudProviderSpec": {
                    "templateVMName": "kkp-ubuntu-22.04",
                    "cpus": 2,
                    "memoryMB": 4096,
                    "diskSizeGB": 10,
                    "allowInsecure": true
                  },
                  "operatingSystem": "ubuntu",
                  "operatingSystemSpec": {
                    "distUpgradeOnBoot": false
                  }
                }
              },
              "versions": {
                "kubelet": ""
              }
            }
          }
        }
      }
    presetName: kubermatic-new-dc
    user: tobias.schneck@kubermatic.com
  labels:
    is-credential-preset: "true"
    name: cluster-template-crd-example-vsphere
    project-id: dl6kxzf8br
    scope: project
  name: cluster-template-crd-example-vsphere
spec:
  cloud:
    dc: vsphere
    providerName: vsphere
    vsphere:
      credentialsReference:
        name: credentials-xxx-crd-cluster-id
        namespace: kubermatic
      infraManagementUser: {}
      datastore: vsan
      folder: ""
      password: ""
      storagePolicy: ""
      username: ""
      vmNetName: /Hamburg/network/Default Network
  clusterNetwork:
    dnsDomain: cluster.local
    ipFamily: IPv4
    ipvs:
      strictArp: true
    konnectivityEnabled: true
    nodeCidrMaskSizeIPv4: 24
    nodeLocalDNSCacheEnabled: true
    pods:
      cidrBlocks:
      - 172.25.0.0/16
    proxyMode: ipvs
    services:
      cidrBlocks:
      - 10.240.16.0/20
  cniPlugin:
    type: canal
    version: v3.24
  containerRuntime: containerd
  enableOperatingSystemManager: true
  enableUserSSHKeyAgent: true
  exposeStrategy: Tunneling
  humanReadableName: cluster-template-crd-example-vsphere
  kubernetesDashboard:
    enabled: true
  mla:
    loggingEnabled: true
    monitoringEnabled: true
  opaIntegration:
    enabled: true
    webhookTimeoutSeconds: 10
  pause: false
  version: 1.26.9
