apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationDefinition
metadata:
  name: falco
spec:
  description: Falco is a cloud native runtime security tool for Linux operating systems.
  method: helm
  versions:
  - template:
      source:
        helm:
          chartName: falco
          chartVersion: 3.5.0
          url: https://falcosecurity.github.io/charts
    version: 0.35.1
  defaultValues: {}
