apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationDefinition
metadata:
  name: trivy-operator
spec:
  description: Trivy-Operator is Kubernetes-native security toolkit.
  method: helm
  versions:
  - template:
      source:
        helm:
          chartName: trivy-operator
          chartVersion: 0.15.1
          url: https://aquasecurity.github.io/helm-charts/
    version: 0.15.1
  defaultValues:
    trivy:
      # To specfy that Trivy should ignore all unfixed vulnerabilities, set `ignoredUnfixed` flag to `true`
      ignoreUnfixed: true
