### As reference: https://github.com/metallb/metallb/blob/v0.9.6/manifests/example-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
  labels:
    #needed to ensure config get read in
    metallb-config-version: '{{ .Variables.addressPoolRange | adler32sum }}'
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - {{ .Variables.addressPoolRange }}
